enum ActionTypes {
  LOG_IN_USER_START = 'LOG_IN_USER_START',
  LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS',
  LOG_IN_USER_FAIL = 'LOG_IN_USER_FAIL',
  SET_USER_ID = 'SET_USER_ID',
  GET_USER_DATA_START = 'GET_USER_DATA_START',
  GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL',
}

export { ActionTypes }
